# Generated by Django 3.1.2 on 2020-11-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hukuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jns_hukuman', models.CharField(choices=[(1, 'Ringan'), (2, 'Sedang'), (3, 'Berat')], default=1, max_length=50)),
                ('teguran', models.CharField(max_length=100)),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.ms_pegawai')),
                ('nip_pimpinan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pimpinan', to='task.ms_pegawai')),
            ],
        ),
    ]
