# Generated by Django 3.1.2 on 2020-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_hukuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='selisih',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hukuman',
            name='jns_hukuman',
            field=models.CharField(choices=[('rn', 'Ringan'), ('sd', 'Sedang'), ('br', 'Berat')], default='rn', max_length=50),
        ),
    ]
